<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5O3KB1E" ignored="0" name="Default test" tests="1" failures="1" timestamp="21 Oct 2019 02:02:13 GMT" time="259.526" errors="0">
  <testcase name="loginFailTest" time="233.109" classname="css.com.HFR.Tests.FaceBookLoginTest">
    <failure type="java.lang.AssertionError" message="Failed to locate element by [By.name: email]. See screenshots
[Ljava.lang.StackTraceElement;@53bc1328">
      <![CDATA[java.lang.AssertionError: Failed to locate element by [By.name: email]. See screenshots
[Ljava.lang.StackTraceElement;@53bc1328
	at org.testng.Assert.fail(Assert.java:93)
	at css.com.GlobalPageHelpers.findWebElementBy(GlobalPageHelpers.java:71)
	at css.com.GlobalPageHelpers.setField(GlobalPageHelpers.java:55)
	at css.com.GlobalPageHelpers.setField(GlobalPageHelpers.java:50)
	at css.com.HFR.Pages.HomePage.loginFacebook(HomePage.java:24)
	at css.com.HFR.Tests.FaceBookLoginTest.loginFailTest(FaceBookLoginTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- loginFailTest -->
</testsuite> <!-- Default test -->
